#!/usr/bin/env bash
#file ot not to file
F=school

if [ -e "$F" ]
then
    echo "$F exists."
    if [ -f "$F" ]
    then
	echo "$F is regular file"
    else
	:

       fi
    if [ -s "$F" ]
       
    then
	echo "$F file is empty"
    else
	echo "$F file is not empty"
	fi
else 
    echo "$F file does not exist."
fi
