#!/usr/bin/env bash
#add elif
n=0
while [ $n -lt 10 ]
do
    if [[ $n -eq 3 ]]
    then
	echo "Bad luck"
    elif [[ $n -eq 7 ]]
	
    then
	echo "Good luck"
    else
	echo "Best School"
fi
    	((n++))
done
