#!/usr/bin/env bash
#file not or not to file 
F=school

if [ -e "$F" ]
then
    echo "$F file exists"
   
    if [ -s "$F" ]
       
    then
	echo "$F file is not empty"
    else
	echo "$F file is  empty"
    fi

     if [ -f "$F" ]
    then
	echo "$F is a regular file"
    else
	:

       fi
else 
    echo "$F file does not exist"
fi
