#!/usr/bin/env bash
#file not or not to file 
S=school

if [ -e "$S" ]
then
    echo "$S file exists"
   
    if [ -s "$S" ]
       
    then
	echo "$S file is not empty"
    else
	echo "$F file is empty"
    fi

     if [ -f "$S" ]
    then
	echo "$S is a regular file"
    else
	:

       fi
else 
    echo "$S file does not exist"
fi
