#!/usr/bin/env bash
#
touch /var/run/myscript.pid "$$"
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"' SIGTERM | rm /var/run/myscript.pid 
    trap 'echo "Y U no love me?!"' SIGINT | rm /var/run/myscript.pid
done 
